MODEL:
  TYPE: groupmixformer
  NAME: groupmixformer
  GMA:
    EMBEDDING_DIMS: [40, 80, 160, 160]
    SERIAL_DEPTHS: [3, 3, 12, 4]
    MLP_RATIOS: [4, 4, 4, 4]
    DROP_PATH_RATE: 0.1
  # PRETRAINED: ./pretrained/groupmixformer_miny.pth ## uncomment this line to use pretrained model
TRAIN:
  EPOCHS: 300
  WARMUP_EPOCHS: 20

